### ISSUE TITLE
Can't use PostgreSQL

### ISSUE THREAD

**Issue by BratishkaErik** [ElCholoGamer/userlogin#28]
[19:57:36] [Craft Scheduler Thread - 6/INFO]: [UserLogin] JDBC driver for database missing: org.postgresql.Driver
[19:57:36] [Craft Scheduler Thread - 6/WARN]: java.lang.ClassNotFoundException: org.postgresql.Driver
[19:57:36] [Craft Scheduler Thread - 6/WARN]:   at java.base/java.lang.Class.forNameImpl(Native Method)
[19:57:36] [Craft Scheduler Thread - 6/WARN]:   at java.base/java.lang.Class.forName(Unknown Source)
[19:57:36] [Craft Scheduler Thread - 6/WARN]:   at <unknown class>.connect(SQLDatabase.java:32) 
[19:57:36] [Craft Scheduler Thread - 6/WARN]:   at <unknown class>.connect(PostgreSQL.java:18) 
[19:57:36] [Craft Scheduler Thread - 6/WARN]:   at com.elchologamer.userlogin.UserLogin.connectDatabase(UserLogin.java:141)
[19:57:36] [Craft Scheduler Thread - 6/WARN]:   at <unknown class>.run(Unknown Source)
[19:57:36] [Craft Scheduler Thread - 6/WARN]:   at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[19:57:36] [Craft Scheduler Thread - 6/WARN]:   at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[19:57:36] [Craft Scheduler Thread - 6/WARN]:   at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[19:57:36] [Craft Scheduler Thread - 6/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[19:57:36] [Craft Scheduler Thread - 6/WARN]:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[19:57:36] [Craft Scheduler Thread - 6/WARN]:   at java.base/java.lang.Thread.run(Unknown Source)

**Comment by ElCholoGamer** [comment]
This is intended. As of v2.12.0, it's necessary to add the PostgreSQL driver to the classpath.

**Comment by BratishkaErik** [comment]
ok
