### ISSUE TITLE
Crash on Paper 1.8.8

### ISSUE THREAD

**Issue by Aiq0** [ElCholoGamer/userlogin#39]
As title suggests, plugin crashes on start when using Paper 1.8.8.

Relevant output:

```
[13:49:31 INFO]: [UserLogin] Enabling UserLogin v2.13.1
[13:49:31 ERROR]: Error occurred while enabling UserLogin v2.13.1 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.configuration.file.FileConfiguration.contains(Ljava/lang/String;Z)Z
	at com.elchologamer.userlogin.manager.LangManager.createDefault(LangManager.java:49) ~[?:?]
	at com.elchologamer.userlogin.manager.LangManager.reload(LangManager.java:65) ~[?:?]
	at com.elchologamer.userlogin.UserLogin.reloadPlugin(UserLogin.java:124) ~[?:?]
	at com.elchologamer.userlogin.UserLogin.onEnable(UserLogin.java:47) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [patched.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [patched.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [patched.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
[13:49:31 INFO]: [UserLogin] Disabling UserLogin v2.13.1
```

**Comment by Grazen0** [comment]
Yes, it's a compatibility bug with the old Minecraft versions. Will be working on this 👍
