### ISSUE TITLE
Critical

### ISSUE THREAD

**Issue by ghost** [ElCholoGamer/userlogin#46]
[15:23:26 WARN]: [UserLogin] Plugin UserLogin v2.13.1 generated an exception while executing task 130
java.lang.IllegalStateException: Asynchronous player kick!
at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.kickPlayer(CraftPlayer.java:329) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at com.elchologamer.userlogin.ULPlayer.onLoginAttempt(ULPlayer.java:198) ~[?:?]
at com.elchologamer.userlogin.command.LoginCommand.authenticate(LoginCommand.java:25) ~[?:?]
at com.elchologamer.userlogin.command.AuthCommand.asyncRun(AuthCommand.java:43) ~[?:?]
at com.elchologamer.userlogin.command.base.AsyncCommand.lambda$run$0(AsyncCommand.java:18) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Dionysus-"42ce9ca"]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_312]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_312]
at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]

Paper/Dionosys/Spigot dont working kick command on error passworld

**Comment by ghost** [comment]
default cfg

**Comment by ghost** [comment]
fix today and give me plsssssssss

**Comment by ghost** [comment]
plugin good.
